### ISSUE TITLE
Ideas and deprecations for next major release 4.0

### ISSUE THREAD

**Issue by ramunasd** [php-amqplib/php-amqplib#662]
Feel free to comment and suggest what can be changed/refactored to make things more fluent and consistent in next major version.

- [ ] Use one immutable object for all connection options and reuse it in all connection types
- [ ] Merge StreamIO and SocketIO into corresponding connection class
- [ ] Connection class should not extend channel class therefore no calls to protected methods
- [ ] Split AMQPChannel->wait() into to separate blocking and non-blocking methods, separate method for internal use
- [ ] Refactor existing TODO
- [ ] Deprecate AMQPSSLConnection, activate SSL context whenever protocol is secure
- [x] Deprecate public properties in connection and channel classes #673 
- [x] Deprecate global constants #732
- [ ] PSR-12 code style
- [ ] Changelog standard https://keepachangelog.com/en/1.0.0/
- [x] Remove bcmath dependency #573 #694 #695 #737 #754 
- [ ] PHP > 7.0, typehints for most public methods
- [ ] Use https://github.com/reactphp/socket or https://github.com/amphp/socket for low level non-blocking IO operations

**Comment by MJTheOne** [comment]
You speak of an immutable object for the connection types, but what about the 'delivery_info' on an AMQPMessage? Why not make an object out of everything that should be accessible in stead of arrays?

Like the method 'getDeliveryTag' which is already setting a step towards a better system of trying to get the information for situations like this:
```
/** @var AMQPChannel $channel */
$channel = $message->delivery_info['channel'];
$channel->basic_ack($message->delivery_info['delivery_tag']);
```

That could (now) be replaced by this:
```
/** @var AMQPChannel $channel */
$channel = $message->delivery_info['channel'];
$channel->basic_ack($message->getDeliveryTag());
```

Situation I (and probably many others) would prefer:
```
// No @var is needed anymore because getChannel has a returnType
$channel = $message->getChannel();
$channel->basic_ack($message->getDeliveryTag());
```

**Comment by ramunasd** [comment]
@MJTheOne thanks for suggesting. I have this on my mind for a long time. I guess next minor release will have something like:
```
$message->ack();
```

**Comment by MJTheOne** [comment]
That would simplify things even further! If you need some help in implementing OO / Value Objects I'd be happy to help :)

**Comment by lucasRolff** [comment]
I'd love something like batch-consumers that are available in your Symfony2 bundle: https://github.com/php-amqplib/RabbitMqBundle#batch-consumers

the use case I have is something like this:
- We have 100k incoming messages, all messages contain a string that has to be processed, a "string ID" and a callback URL
- Each string is processed, message after message
- Only wanna do a "callback" to the callback URL every X messages containing the "string ID" from every msg (since the callback system may not be able to handle the number of requests that we can process per second by the consumers).

I'm trying to find a nice way of doing it currently with php-amqplib directly but a bit lost.

**Comment by LeonMelis** [comment]
@MJTheOne  The `delivery_info` property is already declared as deprecated in 2.x, you shouldn't access it anyway.

To access the delivery tag (and other properties), you should already be using the `get` method:

```php
$delivery_tag = $message->get('delivery_tag');
$channel = $message->get('channel');
// etc
```
I assume the maintainers annotated the `delivery_info` property with a deprecation tag because they want to eventually make the property private. If so, the 3.0 release would be a great time to do so.

**Comment by liborm85** [comment]
All PRs for compatibility with PHP 8.0 are closed due to alleged BC. In https://github.com/php-amqplib/php-amqplib/pull/858#issuecomment-751369700 is information about PHP 8.0 support in next major version 3.0.

@nubeiro @lukebakken @ramunasd When is expected finish version 3.0 with support PHP 8.0? According to branch `dev-3.x`, there is no development. PHP 8.0 support is required.

**Comment by ramunasd** [comment]
@liborm85 there is no confirmed roadmap or deadline for next major version. Quite a lot of things must be changed and well tested. Please use mailing list[1] or gitter channel[2] for specific version support related questions.

[1] https://groups.google.com/forum/#!forum/php-amqplib-devel
[2] https://gitter.im/php-amqplib/RabbitMqBundle

**Comment by liborm85** [comment]
@ramunasd If isn't deadline for release next major version with support PHP 8.0, its big problem, because PHP 8.0 is released and this library has no support for it.
